# Generated by Django 6.0.2 on 2026-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='visibility',
            field=models.CharField(blank=True, default='public', max_length=20),
        ),
    ]
