# Generated by Django 6.0.2 on 2026-03-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_sprint_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='sprint.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
